{
 "title": "lomov-monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (resolver) (rate(graphql_http_requests[1m]))"
    }
   ]
  },
  {
   "title": "Neo4j - Node creation speed (ids)[1m]",
   "type": "singlestat",
   "description": "This is in reality the change in neo4j ids.\nIf the transaction is rolled-back nodes will not be created but will increase this gauge.\n\nMaximum speed is set to 30k nodes/sec\nEmpirically we saw this is the maximum handled by the production machine",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(neo4j_ids_in_use_node[1m])"
    }
   ]
  },
  {
   "title": "Neo4j - Relationship creation speed (ids)[1m]",
   "type": "singlestat",
   "description": "This is in reality the change in neo4j ids.\nIf the transaction is rolled-back nodes will not be created but will increase this gauge.\n\nMaximum speed is set to 30k nodes/sec\nEmpirically we saw this is the maximum handled by the production machine",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(neo4j_ids_in_use_relationship[1m])"
    }
   ]
  },
  {
   "title": "Neo4j - Property creation speed (ids)[1m]",
   "type": "singlestat",
   "description": "This is in reality the change in neo4j ids.\nIf the transaction is rolled-back nodes will not be created but will increase this gauge.\n\nMaximum speed is set to 30k nodes/sec\nEmpirically we saw this is the maximum handled by the production machine",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(neo4j_ids_in_use_property[1m])"
    }
   ]
  },
  {
   "title": "Requests counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "graphql_http_requests", "legendFormat": "{{resolver}}" }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(resolver) (rate(graphql_http_error_rate[1m]))"
    }
   ]
  },
  {
   "title": "Nginx - 5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Latency-0.95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, resolver) \n         (rate(graphql_http_requests_latency_bucket[1m]))\n) * 1000\n\n"
    }
   ]
  },
  {
   "title": "Latency-0.5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, resolver) \n         (rate(graphql_http_requests_latency_bucket[1m]))\n) * 1000\n\n",
     "legendFormat": "{{resolver}}"
    }
   ]
  },
  {
   "title": "Latency-0.99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, resolver) \n         (rate(graphql_http_requests_latency_bucket[1m]))\n) * 1000\n\n",
     "legendFormat": "{{resolver}}"
    }
   ]
  },
  {
   "title": "Latency-max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, \n      sum by (le, resolver) \n         (rate(graphql_http_requests_latency_bucket[1m]))\n) * 1000\n\n",
     "legendFormat": "{{resolver}}"
    }
   ]
  },
  {
   "title": "Nginx - latency 0.5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,      sum by (le, status)  (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "Nginx - request  durations by status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Nginx - latency 0.95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95,      sum by (le, status)          (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Nginx - latency 0.99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,      sum by (le, status)          (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Nginx - latency max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1.0,       sum by (le, status)         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Sys - memory usage bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Sys - cpu system seconds total[5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{image!=\"\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Sys - memory utilization by pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod!~\"\"})  by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Sys - cpu user seconds total[5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Neo4j - Counters of Graph Items",
   "type": "graph",
   "description": "Total number of graph items: node, relationships, ...",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_ids_in_use_(node|property|relationship)\"}, \"label\", \"$1\", \"__name__\", \"neo4j_ids_in_use_(.+)\")",
     "legendFormat": "# {{label}} {{instance}}"
    },
    {
     "expr": "neo4j_ids_in_use_relationship_type{}",
     "legendFormat": "# relationship type {{instance}}"
    }
   ]
  },
  {
   "title": "Sys - cpu usage seconds total[5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Neo4j - Counters of Graph Items",
   "type": "graph",
   "description": "Total number of graph items: node, relationships, ...",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_ids_in_use_(node|property|relationship)\"}, \"label\", \"$1\", \"__name__\", \"neo4j_ids_in_use_(.+)\")",
     "legendFormat": "# {{label}} {{instance}}"
    },
    {
     "expr": "neo4j_ids_in_use_relationship_type",
     "legendFormat": "# relationship type {{instance}}"
    }
   ]
  }
 ]
}