apiVersion: v1
kind: ConfigMap
metadata:
  name: users-service-config
data:
  NEO4J_BOLT_URI: {{ printf "bolt://%s" .Values.externalNeo4j.neo4jhost }}
  NEO4J_USER: {{ printf "%s" .Values.externalNeo4j.neo4juser }}
---
apiVersion: v1
kind: Secret
metadata:
  name: users-service-secret
type: Opaque
data:
  NEO4J_PASSWORD: {{ printf "%s" .Values.externalNeo4j.neo4jpassword | b64enc | quote}}
  #NEO4J_BOLT_LOGIN_URI: {{ printf "bolt://%s:%s@%s:%s" .Values.externalNeo4j.neo4juser .Values.externalNeo4j.neo4jpassword (include "neo4j.fullname" .) | b64enc | quote }}
  NEO4J_BOLT_LOGIN_URI: {{ printf "bolt://%s:%s@%s:%s" .Values.externalNeo4j.neo4juser .Values.externalNeo4j.neo4jpassword .Values.externalNeo4j.neo4jhost  | b64enc | quote }}