# Default values for users-service-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
revisionHistoryLimit: 0

ingress:
  host: arch.homework
  path: /otusapp($|/)(.*)

image:
  repository: alanlom/users-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: "1.0"

service:
  type: NodePort
  port: 4000

externalNeo4j:
  neo4juser: neo4j
  neo4jpassword: test
  neo4jport: 7687

# For dependency chart
neo4j:
  serviceName: neo4j
  image: neo4j
  imageTag: '3.5.16'
  authEnabled: true
  neo4jPassword: test
  core:
    numberOfServers: 1
    persistentVolume.size: 0.2Gi