apiVersion: v1
kind: ConfigMap
metadata:
  name: users-service-config
data:
  NEO4J_BOLT_URI: bolt://neo4j
  NEO4J_USER: neo4j
---
apiVersion: v1
kind: Secret
metadata:
  name: users-service-secret
type: Opaque
data:
  NEO4J_PASSWORD: dGVzdA==