# Default values for users-service-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
revisionHistoryLimit: 0

ingress:
  host: arch.homework
  path: /otusapp($|/)(.*)
  enabled: true
  hosts:
    - host: arch.homework
      paths: ["/app", "/otusapp($|/)(.*)"]



image:
  repository: alanlom/users-service
  pullPolicy: IfNotPresent
  tag: "monitoring"

imageUtils:
  repository: alanlom/otus-utils
  tag: "1.0"


service:
  type: NodePort
  port: 4000

externalNeo4j:
  neo4juser: neo4j
  neo4jpassword: test
  neo4jport: 7687

metrics:
  serviceMonitor:
    enabled: true

# For dependency chart
neo4jPassword: test

neo4j:
  acceptLicenseAgreement: "yes"
  serviceName: neo4j
  NEO4J_dbms_mode: SINGLE
  # image: neo4j
  # imageTag: '3.5.16'
  authEnabled: false
  neo4jPassword: test
  core:
    numberOfServers: 1
    persistentVolume.size: 0.2Gi
    extraVars:
    - name: 'NEO4J_metrics_prometheus_enabled'
      value: 'true'
    - name: 'NEO4J_dbms_mode'  
      value: 'SINGLE'
    - name: 'NEO4J_metrics_prometheus_endpoint'
      value: '0.0.0.0:7474'
    - name: 'NEO4J_dbms_connector_http_enabled'
      value: 'true'
    - name: 'NEO4J_dbms_connector_https_enabled'
      value: 'true'
    - name: NEO4J_dbms_connector_http_listen__address
      value: ":7000"  
