apiVersion: v1
kind: Service
metadata:
  name: {{ include "users-service-chart.fullname" . }}-memcache
  labels:
    {{- include "users-service-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.memcache.type }}
  ports:
    - port: {{ .Values.services.memcache.port }}
      targetPort: memcache
      protocol: TCP
  selector:
    name: {{ include "users-service-chart.fullname" . }}-memcache
